### ISSUE TITLE
Lasagne not working properly

### ISSUE THREAD

**Issue by gitvicky** [Lasagne/Lasagne#891]
While defining the layers of my network I am getting this error. 

    the_layers = lasagne.layers.DenseLayer(the_layers, num_units=64, nonlinearity=lasagne.layers.nonlinearities.rectify)

AttributeError: 'module' object has no attribute 'nonlinearities'

I am working on Python 2.7, Theano 0.8.0, Lasagne 1.0, nolearn 0.6

**Comment by f0k** [comment]
It should be `lasagne.nonlinearities`, not `lasagne.layers.nonlinearities`. See the documentation: http://lasagne.readthedocs.io/en/latest/modules/nonlinearities.html
