### ISSUE TITLE
What version of Theano should Lasagne require/support?

### ISSUE THREAD

**Issue by ebenolson** [Lasagne/Lasagne#323]
I think Lasagne's `requirements.txt` should point to a git commit, updated with each PR to the latest version. This provides a fairly current Theano, while still making sure we don't pull in changes which might break Lasagne.

Arguments for this:
* 0.7 is several months old, with > 1000 commits since. 
* The last release gap was over 1 year, and I see no reason to expect that to change.
* While Theano's docs ostensibly refer to 0.7, they're actually compiled from master, and contain information on code that doesn't exist in 0.7. I think this is evidence that git is the definitive version.

**Comment by benanne** [comment]
Note: this discussion came up in #320, but it's important enough to give it its own issue since previously there was an implicit agreement to standardize on version 0.7 once it was released.

I'll try to think of my own arguments and counter-arguments later :)

**Comment by ebenolson** [comment]
Along with this, I think it should be a goal to keep Lasagne compatible with Theano master, and patch any problems that arise as soon as possible.

**Comment by dnouri** [comment]
If we go with this, the docs will need fixing.  "pip install Lasagne" will have to be replaced with "pip install -r https://github.com/.../1.0/requirements.txt" and then "pip install Lasagne".  So I'd suggest making a separate pull request for this that also updates the docs.

There's a small trade off there: you can't tell users to "just use pip install" anymore.  But I think that's okay.

It may also trip up some people that use a Git checkout of Lasagne.  If the requirements.txt updates frequently as you do a git pull, I imagine it might happen that you forget to re-run the `pip install -r requirements.txt` to get the latest required Theano.  Maybe worthwhile mentioning that in the docs.

**Comment by f0k** [comment]
Hmm... I'd generally encourage people to use the git version of Theano, but I don't necessarily think it's a good idea to make it a strict requirement. If it doesn't overly complicate matters, a good solution would be to fail gracefully for dependencies on features added since the latest release of Theano. This should make it easier to get people started, and allow people to upgrade Theano to the bleeding-edge version in case they need something that's not available in the latest release.

**Comment by benanne** [comment]
I think I agree with @f0k here.

**Comment by ebenolson** [comment]
> a good solution would be to fail gracefully for dependencies on features added since the latest release of Theano.

This would be messy. Code would be added to do version checks, then need to be removed once Theano releases. 

Also, for tiny feature additions like #320 it might not be terrible, but what about stuff like #310? You could no longer fix problems with Lasagne by getting changes introduced upstream.

**Comment by ebenolson** [comment]
After looking some more, apparently installing requirements directly from git in `setup.py` has been deprecated. If installing/updating Lasagne won't directly alter Theano, I think pinning to a specific commit is not so important, and maybe it's better just to tell people to use Theano master (and depend on our tests to quickly reveal any incompatibilities).

My new suggestion is to remove the Theano requirement from `setup.py`, and add a check on import that Theano is installed and `theano.__version__ >= KNOWN_GOOD_VERSION`, raising a warning with instructions to install from github if not.

**Comment by f0k** [comment]
> Also, for tiny feature additions like #320 it might not be terrible, but what about stuff like #310? You could no longer fix problems with Lasagne by getting changes introduced upstream.

Both don't require the latest Theano in the sense that `import lasagne` and the MNIST example would work fine with Theano 0.7. That's what I'd aim for -- have it be compatible with Theano 0.7, and only fail (not gracefully, just fail) if somebody tries to use a feature that requires a later version. Recommend in the installation instructions to use the latest Theano from git and point out in the FAQ that whenever you encounter a problem, you should try upgrading Theano.
We'd only need to ensure that Travis always uses a version recent enough to pass all tests.

> My new suggestion is to remove the Theano requirement from `setup.py`, and add a check on import that Theano is installed and `theano.__version__ >= KNOWN_GOOD_VERSION`, raising a warning with instructions to install from github if not.

Would be fine by me as a pragmatic solution, but I'd like to hear @dnouri's thoughts.

**Comment by ebenolson** [comment]
Which is easier for a new user?

1. Being forced to type `pip install --upgrade git+git://github.com/Theano/Theano.git`
2. Having Theano 0.7.0 automatically installed, but then sometime later getting an error like this:
   `TypeError: max_pool_2d() got an unexpected keyword argument 'mode'`

Trying to debug this, you go check the [docs](http://deeplearning.net/software/theano/library/tensor/signal/downsample.html), and find the signature is 
    `max_pool_2d(input, ds, ignore_border=False, st=None, padding=(0, 0), mode='max')`
What's going on? For every person who reads the FAQ or figures it out for themselves, I think there will be at least one who opens an issue about the 'bug' here.

Also remember it's not just features but also bugs like the memory leak. I just don't see the benefit to targeting 0.7.0 when we know it will introduce problems.

**Comment by f0k** [comment]
> Trying to debug this, you go check the docs, [...]. What's going on?

Okay, I've got to admit that this is a *very* plausible story!

If we just remove Theano from `requirements.txt`, people will encounter `ImportError: No module named theano` and run `pip install theano`. But along with your suggestion of giving a clear warning that instructs users to run `pip install --upgrade git+git://github.com/Theano/Theano.git` (or the much faster `pip install --upgrade https://github.com/Theano/Theano/archive/master.zip`), this could work. It's a bit unconventional, but we're in an unconventional situation anyway. Daniel, what do you think?

How can we check whether the version is recent enough, though? Like Lasagne, Theano lacks a fully-functional versioning mechanism for versions in between releases. My `theano.__version__` says `0.6.0rc3.dev-dbc7091b93a42e1407d2b97bdae55576edf7db77`, for example, since that was what I had when running `python setup.py develop`. (Okay, I could probably re-run this after every `git pull`.) And there's no way of comparing `0.7.0.dev-d9fc9d7` against `0.7.0.dev-c7855e8`. We'd need to convince Theano to adopt what we couldn't convince the Lasagne core team about (#263).

**Comment by ebenolson** [comment]
You're right, a reliable version check is probably not possible - although maybe Theano could be convinced. But we could at least warn if it's <= 0.7.0., and I think it's still better than autoinstalling something known to be outdated.

**Comment by benanne** [comment]
Agreed, @ebenolson has some pretty convincing arguments. I think I'm okay with recommending Theano from git, but it would still be nice if the most basic things work fine with 0.7.

**Comment by f0k** [comment]
> it would still be nice if the most basic things work fine with 0.7

Agreed, we should only give a warning, but aim to have `import lasagne` and `./mnist.py` still work with whatever is the latest Theano release, as long as this is feasible.

**Comment by benanne** [comment]
Sounds good to me :) Are we making this policy official?

**Comment by dnouri** [comment]
Sorry, just catching up with Lasagne emails.

I'd personally stay away from recommending Github master for a dependency.  There are benefits to keeping a "known good version" of Theano in requirements.txt.  It doesn't mean everyone has to use it, everyone's free to use latest Theano.  And the Lasagne dev team can update the "known good version" of Theano as often as it wants.  Travis also needs a fixed version to test against (or we won't know if test erros are caused by a change in ours or Theano's code); so I think that makes it a no brainer.

I'm not sure what the problem seems to be with installation instructions.  Sure setuptools and pip can be confusing.  But what if we simply ask our "normal users" (i.e. installation instructions for version 1.0) to run these two commands:

```
pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/1.0/requirements.txt
pip install Lasagne
```

Git users can very similarly run:

```
git clone https://github.com/Lasagne/Lasagne.git
cd Lasagne
pip install -r requirements.txt
python setup.py develop
```

And we also tell users it's cool with us if they want to use a newer version of Theano.  How does that sound?

**Comment by benanne** [comment]
Sounds excellent :)

**Comment by f0k** [comment]
What will `pip install -r requirements.txt` do if I've got a different Theano version installed already?

**Comment by dnouri** [comment]
> What will `pip install -r requirements.txt` do if I've got a different Theano version installed already?

It will install the version that's in requirements.txt.  If you want to use dependencies as installed on your system, you can just run `pip install Lasagne`, or roll your own requirements.txt, which is useful for bigger projects with lots of dependencies.  Or maybe more interestingly, here's the commands to run both Theano and Lasagne from Git master:

```
git clone https://github.com/Theano/Theano.git
git clone https://github.com/Lasagne/Lasagne.git
cd Theano
python setup.py develop
cd ../Lasagne
python setup.py develop
```

Seems straight-forward, right?

**Comment by ebenolson** [comment]
I think we need to specify `--upgrade` for pip to install the version from requirements.txt if Theano 0.7 is already installed.

**Comment by dnouri** [comment]
> I think we need to specify `--upgrade` for pip to install the version from requirements.txt if Theano 0.7 is already installed.

It turns out that requiring a `0.8.git` version in the `#egg=` bit in requirements.txt solves that problem:

```
pip install Theano==0.7
echo "git+https://github.com/Theano/Theano.git@36d1eca8#egg=Theano==0.8.git" > requirements.txt
pip install -r requirements.txt  # will install from Git
```

**Comment by f0k** [comment]
> Seems straight-forward, right?

Yes, that's what I use, and I was wondering if `pip install -r requirements.txt` would mess with that. As long as Theano is the only dependency in `requirements.txt`, I can of course just not run that line.

> `git+https://github.com/Theano/Theano.git@36d1eca8#egg=Theano==0.8.git`

So shall we put that into our `requirements.txt`, as part of #321 which triggered it? Or maybe better in a separate PR that also updates the installation instructions a little bit.
